version: "3"
services:
  mysqldb:
    image: mysql
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: default_schema
    ports:
      - "3306:3306"